name: khalti_flutter
description: An official Flutter plugin for Khalti Payment Gateway, with all the necessary interface that make it easy to integrate with your app.
version: 2.0.2
homepage: https://khalti.com/payment-gateway/
documentation: https://docs.khalti.com/
issue_tracker: https://github.com/khalti/khalti-flutter-sdk/issues
repository: https://github.com/khalti/khalti-flutter-sdk/tree/master/packages/khalti_flutter

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  intl:
  khalti:
    git:
      url: https://github.com/queendevelopers/khalti-flutter-sdk.git
      branch: unsound-null-safety
      path: packages/khalti
#dev_dependencies:
#  flutter_lints: ^1.0.4

flutter:
  assets:
    - assets/payment/
    - assets/error/
    - assets/logo/
    - assets/dialog/